BEGIN TRANSACTION;
DROP TABLE IF EXISTS forms;
CREATE TABLE forms (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, name VARCHAR(256), note TEXT);

DROP TABLE IF EXISTS questions;
CREATE TABLE questions (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, form_id INTEGER NOT NULL, content TEXT, imagedata BLOB, FOREIGN KEY (form_id) REFERENCES forms(id));

DROP TABLE IF EXISTS answers;
CREATE TABLE answers (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, question_id INTEGER, content TEXT, correct INTEGER, FOREIGN KEY (question_id) REFERENCES questions(id));

DROP TABLE IF EXISTS groups;
CREATE TABLE groups (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, name TEXT, note TEXT);

DROP TABLE IF EXISTS childs;
CREATE TABLE childs (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, group_id INTEGER, surname VARCHAR(64), name VARCHAR(64), db DATE, note TEXT, FOREIGN KEY (group_id) REFERENCES groups(id));

DROP TABLE IF EXISTS testing;
CREATE TABLE testing (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, tstdate DATE, form_id INTEGER, group_id INTEGER, note TEXT, FOREIGN KEY (form_id) REFERENCES forms(id), FOREIGN KEY (group_id) REFERENCES groups(id));

DROP TABLE IF EXISTS childanswers;
CREATE TABLE childanswers (id INTEGER CONSTRAINT id PRIMARY KEY AUTOINCREMENT, testing_id INTEGER, child_id INTEGER, question_id INTEGER, answer_id INTEGER, FOREIGN KEY (child_id) REFERENCES childs(id), FOREIGN KEY (question_id) REFERENCES questions(id), FOREIGN KEY (answer_id) REFERENCES answers(id));
END TRANSACTION;
